import {
    ArrowDownIcon,
    ArrowUpIcon,
    CoinsIcon,
    CpuIcon,
    HashIcon,
} from "@phosphor-icons/react";
import { useEffect } from "react";
import { formatCost, formatNumber } from "@/utils/ai-usage-formatters";
import LoadingUi from "@/components/loading-ui";
import ErrorUi from "@/components/error-ui";
import AiUsageCard from "@/components/ai-usage/ai-usage-card";
import { useAiUsageStore } from "@/store/admin-store/ai-usage-store";

function AiUsage() {
    const stats = useAiUsageStore((state) => state.stats);
    const loading = useAiUsageStore((state) => state.loading);
    const error = useAiUsageStore((state) => state.error);
    const fetchStats = useAiUsageStore((state) => state.fetchStats);

    useEffect(() => {
        fetchStats();
    }, [fetchStats]);

    if (loading) {
        return <LoadingUi />;
    }

    if (error || !stats) {
        return (
            <ErrorUi
                errorMessage={error || "Cannot get ai usage data"}
                errorDescription="Failed to get ai usage data"
            />
        );
    }
    return (
        <div className=" bg-white px-6 py-4 sm:px-8 lg:px-10">
            <div className="mx-auto max-w-6xl">
                <div className="mb-4">
                    <h1 className="text-3xl font-semibold tracking-tight text-black sm:text-4xl">
                        AI Usage
                    </h1>

                    <p className="mt-2 max-w-2xl text-sm leading-6 text-black/50">
                        Monitor token consumption and estimated AI usage costs across
                        the platform.
                    </p>
                </div>
                <div className="mb-6 overflow-hidden rounded-3xl bg-black text-white">
                    <div className="flex flex-col gap-6 p-7 md:flex-row md:items-center md:justify-between">
                        <div>
                            <div className="mb-4 flex size-11 items-center justify-center rounded-xl bg-white/10">
                                <CpuIcon size={24} weight="duotone" />
                            </div>
                            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-white/50">
                                Total tokens
                            </p>
                            <h2 className="mt-2 text-4xl font-semibold tracking-tight sm:text-5xl">
                                {formatNumber(stats.totalTokens)}
                            </h2>
                            <p className="mt-2 text-sm text-white/50">
                                Combined input and output tokens
                            </p>
                        </div>
                        <div className="flex size-24 shrink-0 items-center justify-center rounded-full border border-white/10 bg-white/6">
                            <HashIcon size={38} weight="bold" />
                        </div>
                    </div>
                </div>

                <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
                    <AiUsageCard
                        count={stats.totalInputTokens}
                        icon={ArrowDownIcon}
                        label="Input"
                        line=" Tokens sent to the AI models"
                        heading="Input Tokens"
                    />
                    <AiUsageCard
                        count={stats.totalOutputTokens}
                        icon={ArrowUpIcon}
                        label="Output"
                        line="Tokens generated by the AI models"
                        heading="Output tokens"
                    />
                    <AiUsageCard
                        cost={formatCost(stats.totalCost)}
                        icon={CoinsIcon}
                        label="Cost"
                        line="Estimated cost based on configured pricing"
                        heading="Tokens cost"
                    />
                </div>
            </div>
        </div>
    );
}

export default AiUsage;
